project:
  type: website
  output-dir: docs

website:
  title: "Scientific Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: portfolio.qmd
        text: Portafolio

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: es


